//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public int ID { get; set; }
        public string flightID { get; set; }
        public string aircID { get; set; }
        public string source { get; set; }
        public string destination { get; set; }
        public decimal fareInfant { get; set; }
        public decimal fareChild { get; set; }
        public decimal fareYouth { get; set; }
        public decimal fareAdult { get; set; }
        public decimal fareSenior { get; set; }
        public string dates { get; set; }
        public string times { get; set; }
        public string reachtime { get; set; }
        public int durationHour { get; set; }
        public int durationMin { get; set; }
        public string mealFreq { get; set; }
    
        public virtual Aircraft Aircraft { get; set; }
    }
}
