//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassengerSeat
    {
        public string resID { get; set; }
        public string seatID { get; set; }
    
        public virtual SeatLabel SeatLabel { get; set; }
    }
}
